spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 31582171da63ffd61b08d439bf5cef73
            client-secret: VMzrT5sCa91XUYRlkUcjla8FMTq4ypv6
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
          google:
            client-id: 456568316712-vtcrfjlol85rbv989goihrjlhgv2on04.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope: profile, email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


logging:
  level:
    org.hibernate.SQL: debug

jwt:
  access-header: Authorization
  refresh-header: Refresh
  secret: corookiecorookiecorookiecorookiecorookiecorookiecorookiecorookiecorookiecorookiecorookiecorookiecorookiecorookiecorookie

client:
  host: localhost
  url: https://i9a402.p.ssafy.io
  endpoint: success